name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SEMANTIC_PATH: .github/actions

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: e25b9f693f67381ac9ac6480bd75a07c902750de
          path: ${{ env.SEMANTIC_PATH }}

      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-clojure
      - uses: ./.github/actions/setup-babashka
      - uses: ./.github/actions/setup-node

      - id: semi
        uses: ./.github/actions/semantic-version
      # - run: npm ci --ignore-scripts
      - run: echo ${{ steps.outputs.semi.next-version }}

      # - name: Run Tests
      #   run: bb run ci


