name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SEMANTIC_PATH: "./.github/actions"

    steps:
      - run: echo $SEMANTIC_PATH
      - run: echo "$SEMANTIC_PATH"
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: 980f54606df6475f660f7954a49605bea0ba7126
          path: "$SEMANTIC_PATH"

      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-clojure
      - uses: ./.github/actions/setup-babashka
      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/semantic-version
      # - run: npm ci --ignore-scripts

      # - name: Run Tests
      #   run: bb run ci


