name: Run unit and end-2-end tests

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  test-java:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      SEMANTIC_PATH: .github/actions

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: v0.0.7
          path: ${{ env.SEMANTIC_PATH }}

      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-clojure
      - uses: ./.github/actions/setup-babashka
      - uses: ./.github/actions/setup-node
      - run: npm ci --ignore-scripts
      - name: Run Tests
        run: bb run ci


