name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: 4e9dd68e2308470420ef794779b8e8a8577db00c
          token: ${{secrets.GITHUB_TOKEN}}
          path: .github/actions

      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-clojure
      - uses: ./.github/actions/setup-babashka
      - uses: ./.github/actions/setup-node

      - run: npm ci --ignore-scripts

      - id: semantic
        uses: ./.github/actions/semantic-version

      - run: |
          echo "current-version= ${{ steps.semantic.outputs.current-version }}"
          echo "next-version= ${{ steps.semantic.outputs.next-version }}"
