name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: d8c42fe9fa72ba12cd7ba86ad2707ebcb81188d3
          path: .github/actions

      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-clojure
      - uses: ./.github/actions/setup-babashka
      - uses: ./.github/actions/setup-node

      - run: npm ci --ignore-scripts

      - id: semantic
        uses: ./.github/actions/semantic-version

      - if: ${{ steps.semantic.outputs.next-version }} != ${{ steps.semantic.outputs.current-version }}
        run: |
         clojure -T:build release-prepare :version "${{ steps.semantic.outputs.next-version }}"

