name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: v0.0.3
          token: ${{secrets.GITHUB_TOKEN}}
          path: .github/actions

      - run: echo ${{ secrets.GITHUB_ACTOR }}

      # - uses: ./.github/actions/setup-java
      # - uses: ./.github/actions/setup-clojure
      # - run: java --version
      # - run: clojrue --version
      # - run: bb --version
