name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: v0.0.1
          token: ${{secrets.GITHUB_TOKEN}}
          path: .github/remote

      - run: ls -al .github/remote
      - uses: ./.github/remote/actions/setup-java
      - run: java --version
