name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: transit-engineering/actions
          ref: v0.0.1
          token: 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
          path: .github/transit

      - run: ls -al ./github/transit
      - uses: ./.github/transit/.github/workflows/setup-java
      - run: java --version
