name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: v0.0.2
          token: ${{secrets.GITHUB_TOKEN}}
          path: .github/actions

      - run: tree .github/actions
      - uses: ./.github/actions/setup-java
      - run: java --version
