name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: transit-engineering/actions
          ref: v0.0.1
          token: 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
          path: .github/transit

      - run: ls -al ./github/transit
      - uses: ./.github/transit/.github/workflows/setup-java
      - run: java --version
