name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: 2b076d1f93931b33bd1898dbf86968446917f278
          token: ${{secrets.GITHUB_TOKEN}}
          path: .github/actions

      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-clojure
      - run: java --version
      - run: clojrue --version
      - run: bb --version
