name: Test java (remove after use)
on: [push]
jobs:
  test-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: kepler16/actions
          ref: 9209e40
          token: ${{secrets.GITHUB_TOKEN}}
          path: .github/actions

      - uses: ./.github/actions/setup-java
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - uses: ./.github/actions/setup-clojure
      - uses: ./.github/actions/setup-babashka

      - run: java --version
      - run: clojure --version
      - run: bb --version
